version: '3.2'
services:
  apache:
    build: .
    env_file:
      - config/app.env
      - config/mysql.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: bind
        source: ./web
        target: /var/www/html
  mysql:
    image: mysql:5.7
    env_file: config/mysql.env
    # see https://hub.docker.com/_/mysql/
    volumes:
      - ./dumps/demo.sql:/docker-entrypoint-initdb.d/demo.sql
  adminer:
    image: adminer # official image is OK
    ports:
      - 8080:8080
    depends_on:
      - mysql
